[package]
name = "malter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3.2"
embedded-hal = "0.2.4"

epd-waveshare = "0.4"
embedded-graphics = "0.6.1"

embedded-text = "0.4.1"
